# drum-processing/.github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v4

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        environment-file: environment-dev.yml
        activate-environment: drum-processing-dev

    - name: Conda info
      shell: bash -l {0}
      run: |
        conda info
        conda list

    - name: Install package
      shell: bash -l {0}
      run: |
        pip install -e .

    - name: Lint with ruff
      shell: bash -l {0}
      run: |
        ruff check drum_processing/ tests/

    

    - name: Type check with mypy
      shell: bash -l {0}
      run: |
        mypy drum_processing

    - name: Test with pytest
      shell: bash -l {0}
      run: |
        pytest tests/ -v --cov=drum_processing --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella

  build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: 3.11
        environment-file: environment-dev.yml
        activate-environment: drum-processing-dev

    - name: Build package
      shell: bash -l {0}
      run: |
        python -m build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist/